### ISSUE TITLE
Autonomous cannot be selected without code in robotcontainer/dashboard.

### ISSUE THREAD

**Issue by KenwoodFox** [FRC-1721/pre2022season#10]
A sendable chooser needs to be implemented or a replacement needs to be installed.

```
make sim
python robot.py sim
20:43:32:395 INFO    : wpilib              : WPILib version 2022.2.1.5
20:43:32:395 INFO    : wpilib              : HAL version 2022.2.1.1
20:43:32:395 INFO    : wpilib              : Running with simulated HAL.
20:43:32:396 INFO    : wpilib              : robotpy-wpimath version 2022.2.1.4
20:43:32:396 INFO    : wpilib              : pyntcore version 2022.2.1.2
20:43:32:396 INFO    : wpilib              : robotpy-commands-v2 version 2022.2.1.1
20:43:32:396 INFO    : wpilib              : robotpy-wpiutil version 2022.2.1.1
20:43:32:396 INFO    : wpilib              : robotpy-halsim-gui version 2022.2.1.0
20:43:32:396 INFO    : wpilib              : robotpy-rev version 2022.0.1
20:43:32:396 INFO    : wpilib              : robotpy-rev-color version 2021.1.2.0
20:43:32:396 INFO    : faulthandler        : registered SIGUSR2 for PID 5528
20:43:32:396 INFO    : halsim_gui          : WPILib HAL Simulation 2022.2.1.0
HAL Extensions: Attempting to load: libhalsim_gui
Simulator GUI Initializing.
Simulator GUI Initialized!
HAL Extensions: Successfully loaded extension
20:43:32:542 WARNING : pyfrc.physics       : Cannot enable physics support, /home/joe/git/pre2022season/rio/physics.py not found
Not loading CameraServerShared

********** Robot program startup complete **********
Default SimulationPeriodic() method... Override me!
20:43:32:778 INFO    : nt                  : server: client CONNECTED: 127.0.0.1 port 39604
20:43:34:485 ERROR   : your.robot          : Unhandled exception
Traceback (most recent call last):
  File "/home/joe/.local/share/virtualenvs/rio-t_s-Nm-J/lib/python3.10/site-packages/wpilib/_impl/start.py", line 124, in _start
    self.robot.startCompetition()
  File "/home/joe/git/pre2022season/rio/robot.py", line 38, in autonomousInit
    self.autonomousCommand = self.container.getAutonomousCommand()
  File "/home/joe/git/pre2022season/rio/robotcontainer.py", line 56, in getAutonomousCommand
    return self.chooser.getSelected()
AttributeError: 'RobotContainer' object has no attribute 'chooser'


Locals at innermost frame:

{'self': <robotcontainer.RobotContainer object at 0x7fc738b8a140>}


20:43:34:485 WARNING : robotpy             : The robot program quit unexpectedly. This is usually due to a code error.
The above stacktrace can help determine where the error occurred.

Warning at Main: Warning: Watchdog not fed within 0.020000s
        at frc::Watchdog::Impl::Main() + 0x22a [0x7fc73d05928a]
        at  + 0xd33c4 [0x7fc73f0a93c4]
        at  + 0x9259 [0x7fc73fd8d259]
        at clone + 0x43 [0x7fc73fea35e3]

Error at PrintLoopOverrunMessage: Error: Loop time of 0.020000s overrun
        at frc::IterativeRobotBase::PrintLoopOverrunMessage() + 0x52 [0x7fc73d013342]
        at frc::Watchdog::Impl::Main() + 0x123 [0x7fc73d059183]
        at  + 0xd33c4 [0x7fc73f0a93c4]
        at  + 0x9259 [0x7fc73fd8d259]
        at clone + 0x43 [0x7fc73fea35e3]

make: *** [Makefile:18: sim] Error 1
```

**Comment by KenwoodFox** [comment]
The code for this bug is here:
https://github.com/FRC-1721/pre2022season/blob/61288a9c3116f100d8955512d94a3772402ea747/rio/robotcontainer.py#L54-L55

And the docs on how to fix it are here:
https://robotpy.readthedocs.io/projects/pynetworktables2js/en/stable/api_util.html#sendablechooser (sendable chooser on the js dashboard)

and here: https://github.com/robotpy/examples/blob/892706b093f3ce9041d44f5c13e677d80a601c63/commands-v2/hatchbot/robotcontainer.py#L48-L53 (Example code of sendable chooser being used to select one or more `commands/autonomous.py` commands)
